# Parameters related to building hip
ARG base_image

FROM ${base_image}
LABEL maintainer="hipsolver-maintainer@amd.com"

ARG user_uid

# Install dependent packages
# Dependencies:
# * hcc-config.cmake: pkg-config
# * tensile: python2.7, python-yaml
# * hipsolver-test: gfortran, googletest
RUN dnf -y update && dnf install -y \
    sudo \
    ca-certificates \
    git \
    make \
    cmake \
    gcc-c++ \
    gcc-gfortran \
    libcxx-devel \
    rpm-build \
    boost-devel \
    && \
    dnf -y clean all

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G wheel --shell /bin/bash jenkins && \
    mkdir -p /etc/sudoers.d/ && \
    echo '%wheel   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd

ARG HIPSOLVER_SRC_ROOT=/usr/local/src/hipSOLVER

# Clone hipsolver repo
RUN mkdir -p ${HIPSOLVER_SRC_ROOT} && cd ${HIPSOLVER_SRC_ROOT} && \
    git clone -b develop --depth=1 https://github.com/ROCmSoftwarePlatform/hipSOLVER . && \

# Build client dependencies and install into /usr/local (LAPACK & GTEST)
    mkdir -p build/deps && cd build/deps && \
    cmake -DBUILD_BOOST=OFF ${HIPSOLVER_SRC_ROOT}/deps && \
    make -j $(nproc) install && \
    rm -rf ${HIPSOLVER_SRC_ROOT}
